spring.application.name=discovery-server
server.port=8085
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false
eureka.client.service-url.defaultZone = http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.client.serviceurl.defaultZone=http://localhost:8085/eureka
eureka.instance.instance-id =${spring.application.name}:${spring.application.instance_id:${random.value}}