spring.application.name=api-gateway
server.port:8090

spring.cloud.gateway.server.webflux.routes[0].id=cliente
spring.cloud.gateway.server.webflux.routes[0].uri=lb://cliente
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/cliente/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-abonos
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-abonos
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/abonos/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-prestamos
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-prestamos
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/prestamos/**

spring.cloud.gateway.server.webflux.routes[3].id=ms-servicios
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-servicios
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/servicios/**

spring.cloud.gateway.server.webflux.routes[4].id=ms-tipo-cuenta
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-tipo-cuenta
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/tipo-cuenta/**

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8085/eureka
eureka.instance.instance-id =${spring.application.name}:${spring.application.instance_id:${random.value}}